"""Tarifario de muebles y constantes de precios."""

PRECIO_MINIMO = 30.0
COSTE_ANCLAJE = 15.0

TARIFARIO = {
    "armario": {
        "keywords": ["armario", "ropero", "placard", "clóset", "pax", "wardrobe", "closet"],
        "precio_base": 90,
        "necesita_anclaje": True,
        "display_name": {"es": "Armario"},
        "reglas_precio": {
            "puerta_extra": 30,
            "suplemento_corredera": 20,
        },
    },
    "canape": {
        "keywords": ["canape", "canapé", "arcón", "canape abatible"],
        "precio_base": 50,
        "necesita_anclaje": False,
        "display_name": {"es": "Canapé Abatible"},
        "reglas_precio": {
            "pequeno": -10,
            "grande": 20,
        },
    },
    "cama": {
        "precio_base": 50,
        "necesita_anclaje": False,
        "keywords": ["cama", "somier", "bed frame", "bed"],
        "display_name": {"es": "Cama"},
        "reglas_precio": {
            "pequeno": -10,
            "grande": 20,
        },
    },
    "comoda": {
        "precio_base": 50,
        "necesita_anclaje": True,
        "keywords": ["cómoda", "cajonera", "dresser", "chest of drawers"],
        "display_name": {"es": "Cómoda"},
    },
    "mesita_noche": {
        "precio_base": 30,
        "necesita_anclaje": False,
        "keywords": ["mesita", "mesilla", "nightstand", "bedside table"],
        "display_name": {"es": "Mesita de Noche"},
    },
    "sofa": {
        "precio_base": 65,
        "necesita_anclaje": False,
        "keywords": ["sofa", "sofá", "sillon", "couch"],
        "display_name": {"es": "Sofá"},
    },
    "mueble_tv": {
        "precio_base": 50,
        "necesita_anclaje": True,
        "keywords": ["mueble tv", "mesa tv", "entertainment center", "tv stand"],
        "display_name": {"es": "Mueble TV"},
    },
    "escritorio": {
        "precio_base": 45,
        "necesita_anclaje": False,
        "keywords": ["escritorio", "mesa estudio", "desk"],
        "display_name": {"es": "Escritorio"},
    },
    "silla": {
        "precio_base": 15,
        "necesita_anclaje": False,
        "keywords": ["silla", "taburete", "chair"],
        "display_name": {"es": "Silla"},
    },
    "vitrina": {
        "precio_base": 99,
        "necesita_anclaje": True,
        "keywords": ["vitrina", "aparador", "estantería", "estanteria", "display cabinet", "cabinet", "bookcase"],
        "display_name": {"es": "Vitrina"},
    },
    "balda": {
        "precio_base": 30,
        "necesita_anclaje": True,
        "keywords": [
            "balda colgada",
            "baldas colgadas",
            "floating shelf",
            "floating shelves",
            "baldas",
            "balda",
            "estantes",
            "estante",
            "repisas",
            "repisa",
        ],
        "display_name": {"es": "Balda"},
    },
    "mesa_comedor": {
        "precio_base": 49,
        "necesita_anclaje": False,
        "keywords": [
            "mesa comedor",
            "mesa de comedor",
            "dining table",
            "mesas",
            "mesa",
            "table",
        ],
        "display_name": {"es": "Mesa"},
    },
    "espejo": {
        "precio_base": 30,
        "necesita_anclaje": True,
        "keywords": ["espejos", "espejo", "mirror"],
        "display_name": {"es": "Espejo"},
    },
    "cabecero": {
        "precio_base": 40,
        "necesita_anclaje": True,
        "keywords": ["cabecero", "cabezal", "headboard"],
        "display_name": {"es": "Cabecero"},
    },
    "soporte_tv": {
        "precio_base": 45,
        "necesita_anclaje": True,
        "keywords": [
            "soporte tv",
            "soporte de tv",
            "soporte television",
            "tv a la pared",
            "televisor a la pared",
            "tv wall mount",
        ],
        "display_name": {"es": "Soporte TV"},
    },
    "kallax": {
        "precio_base": 45,
        "necesita_anclaje": False,
        "keywords": ["kallax", "estanteria cubos", "estantería de cubos", "cubos ikea"],
        "display_name": {"es": "Kallax / cubos"},
    },
    "cama_abatible": {
        "precio_base": 90,
        "necesita_anclaje": True,
        "keywords": ["cama abatible", "cama plegable", "murphy bed"],
        "display_name": {"es": "Cama abatible"},
    },
    "zapatero": {
        "precio_base": 40,
        "necesita_anclaje": False,
        "keywords": ["zapatero", "zapateros"],
        "display_name": {"es": "Zapatero"},
    },
    "mesa_centro": {
        "precio_base": 35,
        "necesita_anclaje": False,
        "keywords": ["mesa de centro", "mesa centro", "coffee table"],
        "display_name": {"es": "Mesa de centro"},
    },
    "litera": {
        "precio_base": 75,
        "necesita_anclaje": False,
        "keywords": ["literas", "litera", "bunk bed"],
        "display_name": {"es": "Litera"},
    },
    "cuna": {
        "precio_base": 45,
        "necesita_anclaje": False,
        "keywords": ["cunas", "cuna", "crib"],
        "display_name": {"es": "Cuna"},
    },
    "mueble_bano": {
        "precio_base": 65,
        "necesita_anclaje": True,
        "keywords": ["mueble de bano", "mueble de baño", "mueble baño", "mueble bano"],
        "display_name": {"es": "Mueble de baño"},
    },
    "cortinas": {
        "precio_base": 30,
        "necesita_anclaje": True,
        "keywords": ["cortinas", "cortina", "riel", "barra de cortina"],
        "display_name": {"es": "Cortinas"},
    },
    "tendedero": {
        "precio_base": 35,
        "necesita_anclaje": True,
        "keywords": ["tendedero", "tendederos", "drying rack"],
        "display_name": {"es": "Tendedero"},
    },
    "otros": {
        "precio_base": 0,
        "necesita_anclaje": False,
        "keywords": [],
        "display_name": {"es": "Otros"},
        "precio_manual": True,
        "solo_admin": True,
    },
}
