"""Create full initial schema with correct ENUMs

Revision ID: abd09aac815a
Revises: 
Create Date: 2025-12-01 15:12:06.445499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd09aac815a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('montador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('zona_servicio', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    op.create_table('trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('precio_calculado', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('cotizacion', 'pendiente', 'aceptado', 'en_progreso', 'revision_cliente', 'completado', 'cancelado', 'incidencia', 'aprobado_cliente_stripe', 'cancelado_incidencia', name='estado_trabajo_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('montador_id', sa.Integer(), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), server_default='stripe', nullable=False),
    sa.Column('imagenes_urls', sa.JSON(), nullable=True),
    sa.Column('etiquetas', sa.JSON(), nullable=True),
    sa.Column('desglose', sa.JSON(), nullable=True),
    sa.Column('foto_finalizacion', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['montador_id'], ['montador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_intent_id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('montador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['montador_id'], ['montador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('montador_id')
    )
    op.create_table('gem_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajo.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gem_transaction')
    op.drop_table('wallet')
    op.drop_table('trabajo')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    op.drop_table('montador')
    op.drop_table('link')
    op.drop_table('cliente')
    # ### end Alembic commands ###
